# Generated by Django 6.0.7 on 2026-08-14 01:09

import apps.checkout.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0004_product_sku_required"),
        ("baskets", "0001_initial"),
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sale_number",
                    models.CharField(
                        default=apps.checkout.models.generate_sale_number,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("payment_method", models.CharField(max_length=32)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PAID", "Payé"),
                            ("FAILED", "Échoué"),
                        ],
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.UUIDField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale",
                        to="baskets.basketsession",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "permissions": [("complete_sale", "Peut finaliser une vente")],
            },
        ),
        migrations.CreateModel(
            name="MatrixScanEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField()),
                (
                    "matrix_id",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4095),
                        ]
                    ),
                ),
                ("frame_errors", models.PositiveSmallIntegerField(default=0)),
                ("copy_disagreements", models.PositiveSmallIntegerField(default=0)),
                (
                    "cell_contrast",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("SELECTED", "Panier sélectionné"),
                            ("UNKNOWN_MATRIX", "Matrice inconnue"),
                            ("NO_OPEN_SESSION", "Aucune session ouverte"),
                            ("ALREADY_SELECTED", "Déjà sélectionné"),
                            ("QUALITY_REJECTED", "Qualité insuffisante"),
                            ("VERSION_CONFLICT", "Conflit de version"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "resulting_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scan_events",
                        to="baskets.basketsession",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scan_events",
                        to="devices.checkoutterminal",
                    ),
                ),
            ],
            options={
                "ordering": ("-received_at",),
                "indexes": [
                    models.Index(
                        fields=["matrix_id", "received_at"],
                        name="checkout_ma_matrix__a5a46c_idx",
                    ),
                    models.Index(
                        fields=["result", "received_at"],
                        name="checkout_ma_result_d694ff_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("terminal", "event_id"),
                        name="checkout_unique_terminal_scan",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("matrix_id__gte", 1), ("matrix_id__lte", 4095)
                        ),
                        name="checkout_matrix_id_1_4095",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SaleLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_sku", models.CharField(max_length=64)),
                ("product_name", models.CharField(max_length=255)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.PositiveIntegerField()),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_lines",
                        to="api.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="checkout.sale",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="checkout_sale_quantity_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("SALE", "Vente"), ("ADJUSTMENT", "Ajustement")],
                        max_length=16,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="api.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="checkout.sale",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["product", "created_at"],
                        name="checkout_st_product_2ad34d_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity", 0), _negated=True),
                        name="checkout_stock_movement_nonzero",
                    )
                ],
            },
        ),
    ]
