# Generated by Django 6.0.7 on 2026-07-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='Code-barres / Identifiant IA')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Prix')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BasketSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, verbose_name='Identifiant de la Raspberry/PC IoT')),
                ('status', models.CharField(choices=[('ACTIVE', 'En cours'), ('VALIDATED', 'Validé'), ('CANCELED', 'Annulé')], default='ACTIVE', max_length=20, verbose_name='État du panier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='baskets', to='api.product', verbose_name='Produits détectés')),
            ],
        ),
    ]
