# Generated by Django 6.0.7 on 2026-08-14 01:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckoutTerminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credential_hash", models.CharField(editable=False, max_length=128)),
                (
                    "terminal_code",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Utilisez 2 à 64 caractères alphanumériques, point, tiret ou soulignement.",
                                regex="^[A-Za-z0-9][A-Za-z0-9._-]{1,63}$",
                            )
                        ],
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("terminal_code",),
            },
        ),
        migrations.CreateModel(
            name="BasketDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credential_hash", models.CharField(editable=False, max_length=128)),
                (
                    "device_code",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Utilisez 2 à 64 caractères alphanumériques, point, tiret ou soulignement.",
                                regex="^[A-Za-z0-9][A-Za-z0-9._-]{1,63}$",
                            )
                        ],
                    ),
                ),
                (
                    "matrix_id",
                    models.PositiveSmallIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4095),
                        ],
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("firmware_version", models.CharField(blank=True, max_length=64)),
                ("last_boot_id", models.CharField(blank=True, max_length=96)),
                (
                    "reset_state",
                    models.CharField(
                        choices=[
                            ("READY", "Prêt"),
                            ("PENDING", "Réinitialisation attendue"),
                        ],
                        default="READY",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("matrix_id",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("matrix_id__gte", 1), ("matrix_id__lte", 4095)
                        ),
                        name="devices_matrix_id_1_4095",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "command_type",
                    models.CharField(
                        choices=[("RESET_SESSION", "Réinitialiser la session")],
                        max_length=32,
                    ),
                ),
                ("session_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACKNOWLEDGED", "Acquittée"),
                            ("CANCELLED", "Annulée"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commands",
                        to="devices.basketdevice",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["device", "status", "created_at"],
                        name="devices_dev_device__d88676_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device", "command_type", "session_id"),
                        name="devices_unique_command_session",
                    )
                ],
            },
        ),
    ]
