# Generated by Django 6.0.7 on 2026-08-14 01:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0004_product_sku_required"),
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BasketSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Ouvert"),
                            ("CHECKOUT_PENDING", "À vérifier en caisse"),
                            ("COMPLETED", "Terminé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="OPEN",
                        max_length=24,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checkout_started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="devices.basketdevice",
                    ),
                ),
                (
                    "selected_terminal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selected_sessions",
                        to="devices.checkoutterminal",
                    ),
                ),
            ],
            options={
                "ordering": ("-opened_at",),
                "permissions": [
                    ("correct_basket", "Peut corriger les lignes d'un panier"),
                    ("release_basket", "Peut libérer un panier de la caisse"),
                    ("cancel_basket", "Peut annuler un panier"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BasketLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ]
                    ),
                ),
                (
                    "unit_price_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="v1_basket_lines",
                        to="api.product",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="baskets.basketsession",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="BasketCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_id", models.BigIntegerField(blank=True, null=True)),
                ("action", models.CharField(max_length=32)),
                ("reason", models.CharField(max_length=255)),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="basket_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="baskets.basketsession",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="DetectionEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_id", models.UUIDField()),
                ("boot_id", models.CharField(max_length=96)),
                ("sequence", models.PositiveBigIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ITEM_ADDED", "Article ajouté"),
                            ("ITEM_REMOVED", "Article retiré"),
                        ],
                        max_length=16,
                    ),
                ),
                ("detected_label", models.CharField(max_length=128)),
                ("confidence", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                ("model_version", models.CharField(blank=True, max_length=64)),
                ("captured_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Appliqué"),
                            ("UNKNOWN_LABEL", "Label inconnu"),
                            ("BASKET_LOCKED", "Panier verrouillé"),
                            ("RESET_PENDING", "Reset en attente"),
                            ("INVALID_REMOVAL", "Retrait invalide"),
                            ("VERSION_CONFLICT", "Conflit de version"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "resulting_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "resulting_line_quantity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_legacy", models.BooleanField(default=False)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="devices.basketdevice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detection_events",
                        to="api.product",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="baskets.basketsession",
                    ),
                ),
            ],
            options={
                "ordering": ("received_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="basketsession",
            index=models.Index(
                fields=["device", "status"], name="baskets_bas_device__3b9a78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="basketsession",
            index=models.Index(
                fields=["status", "updated_at"], name="baskets_bas_status_a64151_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="basketsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("OPEN", "CHECKOUT_PENDING"))),
                fields=("device",),
                name="baskets_one_active_session_per_device",
            ),
        ),
        migrations.AddConstraint(
            model_name="basketline",
            constraint=models.UniqueConstraint(
                fields=("session", "product"), name="baskets_unique_product_per_session"
            ),
        ),
        migrations.AddConstraint(
            model_name="basketline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="baskets_line_quantity_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="detectionevent",
            index=models.Index(
                fields=["device", "boot_id", "sequence"],
                name="baskets_det_device__0cfe33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detectionevent",
            index=models.Index(
                fields=["result", "received_at"], name="baskets_det_result_18ad53_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="detectionevent",
            constraint=models.UniqueConstraint(
                fields=("device", "event_id"), name="baskets_unique_device_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="detectionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="baskets_confidence_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="detectionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1), ("quantity__lte", 20)),
                name="baskets_event_quantity_1_20",
            ),
        ),
    ]
