# Generated by Codex on 2026-08-19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baskets", "0002_basketsession_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="UncataloguedBasketLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detected_label", models.CharField(max_length=128)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="uncatalogued_lines",
                        to="baskets.basketsession",
                    ),
                ),
            ],
            options={"ordering": ("created_at", "id")},
        ),
        migrations.AlterField(
            model_name="detectionevent",
            name="result",
            field=models.CharField(
                choices=[
                    ("APPLIED", "Appliqué"),
                    ("UNCATALOGUED_OBJECT", "Objet non répertorié ajouté"),
                    ("UNKNOWN_LABEL", "Label inconnu"),
                    ("BASKET_LOCKED", "Panier verrouillé"),
                    ("RESET_PENDING", "Reset en attente"),
                    ("INVALID_REMOVAL", "Retrait invalide"),
                    ("VERSION_CONFLICT", "Conflit de version"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="uncataloguedbasketline",
            constraint=models.UniqueConstraint(
                fields=("session", "detected_label"),
                name="baskets_unique_uncatalogued_label_per_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="uncataloguedbasketline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="baskets_uncatalogued_line_quantity_positive",
            ),
        ),
    ]
