# Generated by Django 6.0.7 on 2026-08-18 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
        ("wallets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RfidEnrollmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("APPROVED", "Acceptée"),
                            ("REJECTED", "Refusée"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("seen_count", models.PositiveIntegerField(default=1)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfid_enrollment_requests",
                        to="wallets.customer",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfid_enrollment_requests",
                        to="devices.basketdevice",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_rfid_enrollment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-last_seen_at", "-id"),
                "permissions": [
                    (
                        "approve_rfid_enrollment",
                        "Peut accepter une demande d'enrôlement RFID",
                    )
                ],
                "indexes": [
                    models.Index(
                        fields=["status", "last_seen_at"],
                        name="wallets_rfi_status_798b3e_idx",
                    ),
                    models.Index(
                        fields=["device", "status"],
                        name="wallets_rfi_device__b2cc32_idx",
                    ),
                ],
            },
        ),
    ]
