# Generated by Django 6.0.7 on 2026-08-20 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baskets", "0003_uncatalogued_basket_lines"),
        ("checkout", "0002_sale_payment_device_alter_sale_cashier_and_more"),
        ("devices", "0002_remove_basketdevice_credential_hash"),
        ("wallets", "0002_rfid_enrollment_requests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RfidPaymentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.UUIDField(unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "balance_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("session_version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Confirmation attendue"),
                            ("INSUFFICIENT_FUNDS", "Solde insuffisant"),
                            ("APPROVED", "Confirmée"),
                            ("REJECTED", "Refusée"),
                            ("CANCELLED", "Annulée"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_requests",
                        to="wallets.rfidcard",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfid_payment_requests",
                        to="devices.basketdevice",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_rfid_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sale",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfid_payment_request",
                        to="checkout.sale",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfid_payment_request",
                        to="baskets.basketsession",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_requests",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ("-requested_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "requested_at"],
                        name="wallets_rfi_status_1203c8_idx",
                    )
                ],
            },
        ),
    ]
