# Generated by Django 6.0.7 on 2026-08-14 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0004_product_sku_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisionLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=128)),
                (
                    "model_version",
                    models.CharField(
                        blank=True,
                        help_text="Vide signifie que le label est valable pour toutes les versions du modèle.",
                        max_length=64,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vision_labels",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "ordering": ("label", "model_version"),
                "indexes": [
                    models.Index(
                        fields=["label", "is_active"],
                        name="catalog_vis_label_454fed_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("label", "model_version"),
                        name="catalog_unique_label_version",
                    )
                ],
            },
        ),
    ]
